# Generated by Django 5.0.7 on 2024-07-17 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "published",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(3000),
                        ]
                    ),
                ),
                (
                    "pages",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "frontcover",
                    models.ImageField(blank=True, null=True, upload_to="frontcovers"),
                ),
                ("genre", models.TextField(max_length=2550)),
                ("keypoints", models.TextField(blank=True, max_length=25500)),
            ],
        ),
    ]
