# Generated by Django 5.0.7 on 2024-07-18 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
            preserve_default=False,
        ),
    ]
